name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        cd ..
    
    - name: Install dependencies
      run: |
        cd vcpkg
        .\vcpkg install glfw3:x64-windows
        .\vcpkg install glm:x64-windows
        cd ..
    
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-tutorial-triangle-windows
        path: build/Release/vulkan-tutorial-triangle.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libvulkan-dev
    
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        cd ..
    
    - name: Install dependencies
      run: |
        cd vcpkg
        ./vcpkg install glfw3
        ./vcpkg install glm
        cd ..
    
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-tutorial-triangle-ubuntu
        path: build/vulkan-tutorial-triangle

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install cmake vulkan-headers
    
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        cd ..
    
    - name: Install dependencies
      run: |
        cd vcpkg
        ./vcpkg install glfw3
        ./vcpkg install glm
        cd ..
    
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-tutorial-triangle-macos
        path: build/vulkan-tutorial-triangle 